create table public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null,
  size text not null check (size in ('S','M','L','XL','XXL')),
  quantity integer not null check (quantity between 1 and 20),
  amount integer not null,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

-- Public users cannot read bookings. Server uses the service-role key.
create policy "No public select" on public.bookings
for select to anon using (false);

-- Admin users can read bookings after Supabase Auth login.
create policy "Authenticated admins can read" on public.bookings
for select to authenticated using (true);

-- No browser insert/update/delete policies are intentionally created.
